export const questions = [
  "2 Year Green Card to Permanent",
  "Asylum",
  "Biden Parole",
  "Change of Status",
  "Citizenship",
  "Family Petition",
  "Fiancé Visa",
  "Renew 10 Year Green Card",
  "T.P.S",
  "Travel Document",
  "U Visa",
  "Visa Center",
  "Widow(er)/VAWA",
  "Work Permit",
];

export const routeMapping = {
  [questions[0]]: "/doc/greencardtopermanent",
  [questions[1]]: "/doc/asylum",
  [questions[2]]: "/doc/bidenparole",
  [questions[3]]: "/doc/changeofstatus",
  [questions[4]]: "/doc/citizenship",
  [questions[5]]: "/doc/family-petition",
  [questions[6]]: "/doc/fiancevisa",
  [questions[7]]: "/doc/renew10yeargreencard",
  [questions[8]]: "/doc/temporaryprotectivestatus",
  [questions[9]]: "/doc/traveldocument",
  [questions[10]]: "/doc/uvisa",
  [questions[11]]: "/doc/visacenter",
  [questions[12]]: "/doc/widowervawa",
  [questions[13]]: "/doc/workpermit",
};
